/** 잔 리스트 탭 — 내 저장 폴더 그리드 (낮은 행 · 제목과 개수 한 줄) */
export const listSavedFolderStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "10px",
    width: "100%",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
    justifyItems: "stretch",
    alignItems: "start",
  },
  folderDeleteBarWrap: {
    width: "100%",
    maxWidth: "320px",
    marginTop: "12px",
    marginLeft: "auto",
    marginRight: "auto",
    boxSizing: "border-box",
  },
  folderDeleteBarBtn: {
    width: "100%",
    margin: 0,
    padding: "10px 12px",
    border: "1px solid rgba(231,76,60,0.55)",
    borderRadius: "8px",
    background: "rgba(231,76,60,0.2)",
    color: "#ffb4a8",
    fontSize: "12px",
    fontWeight: 700,
    lineHeight: 1.3,
    cursor: "pointer",
    fontFamily: "inherit",
    display: "block",
    textAlign: "center",
    boxSizing: "border-box",
  },
  folderBtn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    padding: "5px 6px",
    borderRadius: "8px",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    minHeight: "36px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)",
    position: "relative",
    zIndex: 10,
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    font: "inherit",
    textAlign: "left",
    borderStyle: "solid",
    borderWidth: 2,
  },
  folderBtnActive: { transform: "scale(0.95)" },
  fIcon: { fontSize: "13px", lineHeight: 1, flexShrink: 0 },
  fLabel: {
    fontSize: "10px",
    fontWeight: "bold",
    lineHeight: 1.2,
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "left",
  },
  fCountInline: { fontWeight: 700, opacity: 0.92 },
  addBtn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    padding: "5px 6px",
    border: "2px dashed rgba(255, 255, 255, 0.3)",
    borderRadius: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    cursor: "pointer",
    minHeight: "36px",
    color: "rgba(255, 255, 255, 0.6)",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    font: "inherit",
  },
  addIcon: { fontSize: "13px", lineHeight: 1, flexShrink: 0 },
  addTextInline: {
    fontSize: "10px",
    fontWeight: "bold",
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
    flex: 1,
    textAlign: "left",
  },
  newFolderBox: {
    marginTop: "10px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px",
    border: "2px solid #3498DB",
    borderRadius: "8px",
    backgroundColor: "#1a1a1a",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
  },
  newFolderInput: {
    padding: "6px 8px",
    border: "1px solid #333",
    borderRadius: "4px",
    backgroundColor: "#252525",
    color: "#ffffff",
    fontSize: "12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  newFolderActions: { display: "flex", gap: "6px", justifyContent: "flex-end" },
  newFolderOk: {
    backgroundColor: "#3498DB",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    fontSize: "12px",
    cursor: "pointer",
  },
  newFolderCancel: {
    backgroundColor: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    fontSize: "12px",
    cursor: "pointer",
  },
  savedFoldersCollapseTrigger: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    padding: "4px 2px",
    margin: 0,
    border: "none",
    borderRadius: "6px",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    font: "inherit",
    textAlign: "left",
  },
  savedFoldersChevron: {
    fontSize: "9px",
    lineHeight: 1,
    opacity: 0.65,
    flexShrink: 0,
  },
  editToggleBtn: {
    flexShrink: 0,
    fontSize: "11px",
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.25)",
    background: "rgba(255,255,255,0.08)",
    color: "rgba(255,255,255,0.88)",
    cursor: "pointer",
  },
  editPanel: {
    marginTop: "12px",
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(0,0,0,0.22)",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
    width: "100%",
    boxSizing: "border-box",
  },
  editHint: {
    fontSize: "11px",
    color: "rgba(255,255,255,0.5)",
    margin: 0,
    lineHeight: 1.45,
  },
  folderEditWrap: {
    marginTop: "12px",
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid rgba(52,152,219,0.45)",
    backgroundColor: "rgba(0,0,0,0.28)",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
    width: "100%",
    boxSizing: "border-box",
  },
  folderEditTitle: {
    fontSize: "11px",
    fontWeight: 700,
    color: "rgba(255,255,255,0.75)",
    marginBottom: "8px",
    textAlign: "left",
  },
  folderEditRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    marginBottom: "10px",
  },
  folderEditIconInput: {
    width: "44px",
    flexShrink: 0,
    padding: "6px 6px",
    border: "1px solid #444",
    borderRadius: "6px",
    backgroundColor: "#252525",
    color: "#fff",
    fontSize: "16px",
    textAlign: "center",
    outline: "none",
    boxSizing: "border-box",
  },
  folderEditNameInput: {
    flex: 1,
    minWidth: 0,
    padding: "6px 8px",
    border: "1px solid #444",
    borderRadius: "6px",
    backgroundColor: "#252525",
    color: "#fff",
    fontSize: "12px",
    outline: "none",
    boxSizing: "border-box",
  },
  folderEditColorRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginBottom: "10px",
    justifyContent: "flex-start",
  },
  folderEditColorBtn: {
    width: "22px",
    height: "22px",
    borderRadius: "6px",
    border: "none",
    padding: 0,
    cursor: "pointer",
    flexShrink: 0,
  },
  folderEditSaveBtn: {
    width: "100%",
    margin: 0,
    padding: "9px 12px",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#3498DB",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
};
