/** 잔 올리기 — 폴더 다중 선택 (SaveModal과 유사) */
export const addPlaceFolderPickerStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "8px",
    width: "100%",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
    justifyItems: "stretch",
  },
  btnBase: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    padding: "5px 6px",
    minHeight: "36px",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: 2,
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    font: "inherit",
    textAlign: "left",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
  },
  btnSelected: { transform: "scale(0.98)" },
  fIcon: { fontSize: "13px", lineHeight: 1, flexShrink: 0 },
  fName: {
    fontSize: "10px",
    fontWeight: "bold",
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
    flex: 1,
  },
  addBtn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    padding: "5px 6px",
    minHeight: "36px",
    border: "2px dashed rgba(255, 255, 255, 0.3)",
    borderRadius: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    cursor: "pointer",
    color: "rgba(255, 255, 255, 0.6)",
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    font: "inherit",
  },
  addIcon: { fontSize: "13px", lineHeight: 1, flexShrink: 0 },
  addText: {
    fontSize: "10px",
    fontWeight: "bold",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
    flex: 1,
    textAlign: "left",
  },
  newFolderBox: {
    marginTop: "10px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px",
    border: "2px solid #3498DB",
    borderRadius: "8px",
    backgroundColor: "#1a1a1a",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "320px",
    marginLeft: "auto",
    marginRight: "auto",
  },
  newFolderInput: {
    padding: "6px 8px",
    border: "1px solid #333",
    borderRadius: "4px",
    backgroundColor: "#252525",
    color: "#ffffff",
    fontSize: "12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  newFolderActions: { display: "flex", gap: "6px", justifyContent: "flex-end" },
  newFolderOk: {
    backgroundColor: "#3498DB",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    fontSize: "12px",
    cursor: "pointer",
  },
  newFolderCancel: {
    backgroundColor: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    fontSize: "12px",
    cursor: "pointer",
  },
};
