-- 검색 로그 테이블 생성
CREATE TABLE IF NOT EXISTS search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_query TEXT NOT NULL,
  parsed_region TEXT,
  parsed_alcohol TEXT,
  parsed_vibe TEXT,
  parsed_purpose TEXT,
  search_results_ids TEXT[], -- 배열 형태로 저장
  has_results BOOLEAN NOT NULL DEFAULT false,
  results_count INTEGER NOT NULL DEFAULT 0,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  user_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 장소 클릭 로그 테이블 생성
CREATE TABLE IF NOT EXISTS place_click_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clicked_place_id TEXT NOT NULL,
  clicked_curator_id TEXT,
  place_name TEXT NOT NULL,
  user_id TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source TEXT DEFAULT 'search_result', -- search_result, map_click, bookmark 등
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성 (검색 성능 향상)
CREATE INDEX IF NOT EXISTS idx_search_logs_user_id ON search_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_search_logs_timestamp ON search_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_search_logs_parsed_region ON search_logs(parsed_region);
CREATE INDEX IF NOT EXISTS idx_search_logs_parsed_alcohol ON search_logs(parsed_alcohol);

CREATE INDEX IF NOT EXISTS idx_place_click_logs_user_id ON place_click_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_place_click_logs_timestamp ON place_click_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_place_click_logs_place_id ON place_click_logs(clicked_place_id);

-- RLS (Row Level Security) 정책
ALTER TABLE search_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_click_logs ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 자신의 로그만 볼 수 있도록 정책
CREATE POLICY "Users can view own search logs" ON search_logs
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own search logs" ON search_logs
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can view own place click logs" ON place_click_logs
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own place click logs" ON place_click_logs
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

-- 익명 사용자도 로그를 남길 수 있도록 정책
CREATE POLICY "Anonymous users can insert search logs" ON search_logs
  FOR INSERT WITH CHECK (user_id = 'anonymous');

CREATE POLICY "Anonymous users can insert place click logs" ON place_click_logs
  FOR INSERT WITH CHECK (user_id = 'anonymous');

-- 업데이트 시간 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_search_logs_updated_at BEFORE UPDATE ON search_logs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_place_click_logs_updated_at BEFORE UPDATE ON place_click_logs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
