-- 사용자 선호도 테이블 생성
CREATE TABLE IF NOT EXISTS user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  favorite_alcohol TEXT,
  preferred_vibes TEXT[],
  preferred_regions TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON user_preferences(user_id);
CREATE INDEX IF NOT EXISTS idx_user_preferences_alcohol ON user_preferences(favorite_alcohol);

-- RLS 정책
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 선호도만 볼 수 있음
CREATE POLICY "Users can view own preferences" ON user_preferences
  FOR SELECT USING (auth.uid()::text = user_id);

-- 사용자는 자신의 선호도만 수정할 수 있음
CREATE POLICY "Users can update own preferences" ON user_preferences
  FOR UPDATE USING (auth.uid()::text = user_id);

-- 사용자는 자신의 선호도만 추가할 수 있음
CREATE POLICY "Users can insert own preferences" ON user_preferences
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

-- 업데이트 시간 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_user_preferences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON user_preferences
  FOR EACH ROW EXECUTE FUNCTION update_user_preferences_updated_at();
